import {useEffect,useRef,useState} from 'react';
import {ArrowRight,Layers3,Zap,Activity,Download,Thermometer,ShieldCheck} from 'lucide-react';
import {useStudio} from './StudioState';
import {api,canonical,download,errorText,fmt} from './utils';
import type {Scenario} from './types';
import {VerticalPanel} from './VerticalPanel';
interface FieldStudy {id:string;base_revision:number;kind:string;title:string;unit:string;axes:string[];x:number[];y:number[];values:(number|null)[][];range:number[];diagnostics:Record<string,number|number[]>;notes:string[];input:Scenario;input_sha256:string;resolution:number}
function Alert({text}:{text:string}){return text?<div className="domain-alert" role="alert">{text}</div>:null}
function fieldColor(t:number){const stops=[[21,43,78],[29,98,144],[20,151,143],[184,201,100],[244,162,62],[187,45,43]];const v=Math.max(0,Math.min(.99999,t))*(stops.length-1),i=Math.floor(v),f=v-i;return `rgb(${stops[i].map((x,j)=>Math.round(x+(stops[i+1][j]-x)*f)).join(',')})`}
function FieldMap({study}:{study:FieldStudy}) {
 const canvas=useRef<HTMLCanvasElement>(null);
 useEffect(()=>{const c=canvas.current;if(!c)return;const ctx=c.getContext('2d');if(!ctx)return;const width=850,height=520;const spanX=study.x[study.x.length-1]-study.x[0],spanY=study.y[study.y.length-1]-study.y[0];const pixelsPerUnit=Math.min(720/spanX,415/spanY),pw=spanX*pixelsPerUnit,ph=spanY*pixelsPerUnit,left=(width-pw)/2,top=30+(415-ph)/2;c.dataset.scaleX=String(pw/spanX);c.dataset.scaleY=String(ph/spanY);c.width=width*2;c.height=height*2;ctx.scale(2,2);ctx.fillStyle='#f3f6fa';ctx.fillRect(0,0,width,height);const n=study.resolution;for(let j=0;j<n;j++)for(let i=0;i<n;i++){const value=study.values[j][i];ctx.fillStyle=value===null?'#edf1f5':fieldColor((value-study.range[0])/Math.max(study.range[1]-study.range[0],1e-12));ctx.fillRect(left+i*pw/n,top+j*ph/n,pw/n+.5,ph/n+.5)}ctx.strokeStyle='#5d7085';ctx.strokeRect(left,top,pw,ph);ctx.font='13px system-ui';ctx.fillStyle='#30455c';ctx.textAlign='center';for(let i=0;i<=4;i++){ctx.fillText((study.x[0]+(study.x[n-1]-study.x[0])*i/4).toFixed(2),left+i*pw/4,ph+top+23);ctx.textAlign='right';ctx.fillText((study.y[0]+(study.y[n-1]-study.y[0])*i/4).toFixed(2),left-9,top+i*ph/4+5);ctx.textAlign='center'}ctx.fillText(study.axes[0],left+pw/2,height-13);ctx.save();ctx.translate(16,top+ph/2);ctx.rotate(-Math.PI/2);ctx.fillText(study.axes[1],0,0);ctx.restore()},[study]);
 return <div className="field-map"><canvas ref={canvas} data-testid="field-map-canvas" role="img" aria-label={study.title}/><div className="field-legend"><b>{fmt(study.range[0],2)}</b><span/><b>{fmt(study.range[1],2)} {study.unit}</b></div><small>灰白遮罩表示本求解方法不输出值的区域，不表示场量为零。</small></div>;
}
const diagnostics:Record<string,string>={source_power_w_m:'沉积总热功率 W/m',boundary_flux_w_m:'离散边界净热流 W/m',energy_error_w_m:'热流守恒差 W/m',linear_residual:'线性方程最大残差',reference_rmse_k:'远离热源的解析对照 RMSE / K',coarse_reference_rmse_k:'65 网格对照 RMSE / K',refinement_rmse_ratio:'细网格 / 粗网格误差比',dx_m:'网格 dx / m',dy_m:'网格 dy / m',unknowns:'内部未知数',max_field_kv_mm_rms:'绝缘内表面最大场强 kV/mm RMS',min_field_kv_mm_rms:'绝缘外表面场强 kV/mm RMS',voltage_integral_kv:'电场积分电压 kV',insulation_inner_radius_mm:'绝缘内半径 mm',insulation_outer_radius_mm:'绝缘外半径 mm',uniform_current_density_a_mm2:'均匀电流密度 A/mm²',current_a_rms:'相电流 A RMS',phases_deg:'三相相角 °'};
function CrossSectionFields(){const s=useStudio(),{w}=s;const [kind,setKind]=useState('thermal_fd'),[resolution,setResolution]=useState(65),[out,setOut]=useState<FieldStudy|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');if(!w)return null;const stale=Boolean(out&&canonical(out.input)!==canonical(w.scenario));async function run(){setBusy(true);setError('');try{setOut(await api(`/api/design/${w!.id}/fields`,{expected_revision:w!.revision,kind,resolution},'POST',90000));await s.reload()}catch(e){setError(errorText(e))}finally{setBusy(false)}}return <div className="field-panel"><Alert text={error}/><div className="field-type-cards">{[{id:'thermal_fd',name:'二维土壤热场',tag:'有限差分数值求解',icon:Thermometer},{id:'electric',name:'绝缘电场',tag:'同轴解析 / RMS',icon:Zap},{id:'magnetic',name:'三相外部磁场',tag:'电流相量解析 / RMS',icon:Activity}].map(f=><button key={f.id} className={kind===f.id?'active':''} onClick={()=>setKind(f.id)}><f.icon size={20}/><span><b>{f.name}</b><small>{f.tag}</small></span></button>)}</div><div className="field-controls"><label>采样 / 求解网格<select aria-label="场分析网格" value={resolution} onChange={e=>setResolution(Number(e.target.value))}><option value={65}>65 × 65</option><option value={129}>129 × 129（热场含粗细网格对照）</option></select></label><button className="primary" disabled={busy||s.busy} onClick={()=>void run()}>{busy?'正在求解…':'运行场分析'}<PlaySymbol/></button>{out&&<button disabled={stale} onClick={()=>download('CableSimPro-场分析.json',JSON.stringify(out,null,2),'application/json')}><Download size={14}/>导出快照</button>}</div><div className="domain-notice compact"><ShieldCheck size={17}/><span>热场是真实数值求解；电场和磁场是明确边界下的解析模型。它们不是全耦合多物理场，也没有替代载流量内核。</span></div>{out?<>{stale&&<Alert text="工程已修改，下面仅为历史场图。当前工程需重新求解，导出当前结果已禁用。"/>}<div className={stale?'historical-field':''}><div className="field-result-title"><h3 data-testid="field-title">{out.title}</h3><span>rev.{out.base_revision} · {out.resolution}²</span></div><FieldMap study={out}/></div><div className="field-diagnostics">{Object.entries(out.diagnostics).map(([key,v])=><div key={key}><span>{diagnostics[key]??key}</span><b>{Array.isArray(v)?v.join(' / '):Math.abs(v)>0&&Math.abs(v)<.001?v.toExponential(3):fmt(v,Math.abs(v)<1?5:3)}</b></div>)}</div><section className="domain-method"><h3>求解方法与适用边界</h3>{out.notes.map(n=><p key={n}>{n}</p>)}<code>输入 SHA-256 {out.input_sha256}</code></section></>:<div className="domain-empty"><Layers3 size={36}/><h3>不是给模型涂上渐变色</h3><p>计算完成后显示场量单位、输入快照、模型假设，以及数值热场的残差、守恒和网格对照。</p></div>}<p className="domain-footnote">此处不求解竖井通风、烟囱效应。沿高电热请切换“竖向电热”，并单独提供空气边界。</p></div>}
function PlaySymbol(){return <ArrowRight size={14}/>}

export function FieldPanel(){
 const [domain,setDomain]=useState('cross_section');
 return <><div className="domain-subtabs"><button className={domain==='cross_section'?'active':''} onClick={()=>setDomain('cross_section')}>截面场研究</button><button className={domain==='vertical_air'?'active':''} onClick={()=>setDomain('vertical_air')}>竖向电热</button></div>{domain==='vertical_air'?<VerticalPanel/>:<CrossSectionFields/>}</>;
}
