import {useEffect,useRef,useState} from 'react';
import * as Dialog from '@radix-ui/react-dialog';
import {X,ArrowRight,BookOpen,Check,FileText} from 'lucide-react';
import {useStudio,type Proposal} from './StudioState';
import type {Cable} from './types';
import {api,errorText,fmt} from './utils';
import {engineeringCall} from './runtimeClient';
import CableModelView from './CableModelView';

export function Modal({open,onOpenChange,title,description,children}:{open:boolean;onOpenChange:(b:boolean)=>void;title:string;description:string;children:React.ReactNode}){
 const returnFocus=useRef<HTMLElement|null>(null);
 return <Dialog.Root open={open} onOpenChange={onOpenChange}><Dialog.Portal><Dialog.Overlay className="eng-overlay"/><Dialog.Content className="eng-dialog" onOpenAutoFocus={()=>{returnFocus.current=document.activeElement instanceof HTMLElement?document.activeElement:null}} onCloseAutoFocus={event=>{event.preventDefault();returnFocus.current?.focus()}}><header><div><Dialog.Title>{title}</Dialog.Title><Dialog.Description>{description}</Dialog.Description></div><Dialog.Close asChild><button aria-label="关闭对话框"><X size={20}/></button></Dialog.Close></header>{children}</Dialog.Content></Dialog.Portal></Dialog.Root>;
}
export function ModelGenerator({open,onClose}:{open:boolean;onClose:()=>void}){
 const s=useStudio(),[draft,setDraft]=useState<Cable>(s.w!.scenario.cable),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{if(open){setDraft({...s.w!.scenario.cable});setError('')}},[open]);
 const fields=[['area_mm2','导体截面积','mm²',50,1000],['u0_kv','相对地额定电压 U₀','kV',1,26],['insulation_mm','绝缘标称厚度','mm',2,15],['jacket_mm','外护套厚度','mm',1,8],['conductor_screen_mm','导体屏蔽厚度','mm',.1,2],['insulation_screen_mm','绝缘屏蔽厚度','mm',.1,2],['metallic_screen_mm','金属屏蔽等效厚度','mm',.05,3],['fill_factor','导体填充系数','',.7,1]] as const;
 const valid=fields.every(([k,,,min,max])=>Number.isFinite(draft[k])&&draft[k]>=min&&draft[k]<=max);
 async function generate(){setBusy(true);setError('');try{const p=await engineeringCall<Proposal>(s.w!.id,s.w!.revision,'model.generate',{cable:draft});s.adoptProposal(p);onClose()}catch(e){setError(errorText(e))}finally{setBusy(false)}}
 return <Modal open={open} onOpenChange={o=>{if(!o&&!busy)onClose()}} title="生成电缆模型" description="输入结构尺寸，预览模型，提交后审查参数差异。不会自动推断标准厚度。"><div className="generator-layout"><form onSubmit={e=>{e.preventDefault();void generate()}}><label>电缆名称<input aria-label="生成模型名称" value={draft.name} required maxLength={100} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>导体材料<select aria-label="生成导体材料" value={draft.conductor} onChange={e=>setDraft({...draft,conductor:e.target.value as Cable['conductor']})}><option value="copper">铜</option><option value="aluminium">铝</option></select></label><div className="generator-fields">{fields.map(([key,label,unit,min,max])=><label key={key}>{label}<span className="unit">{unit}</span><input aria-label={'生成'+label} type="number" step="any" min={min} max={max} required value={Number.isFinite(draft[key])?draft[key]:''} onChange={e=>setDraft({...draft,[key]:e.target.value===''?NaN:Number(e.target.value)})}/></label>)}</div><label>20 °C 导体直流电阻 / Ω·km⁻¹<input aria-label="生成厂家电阻" type="number" min={.000001} max={10} step="any" placeholder="留空按材料估算" value={draft.r20_ohm_km??''} onChange={e=>setDraft({...draft,r20_ohm_km:e.target.value===''?null:Number(e.target.value)})}/></label><p className="eng-note">其他物性与损耗参数沿用当前工程，可在“材料参数”中核对。导体改变后，原厂家电阻不能未经确认直接沿用。</p>{error&&<p className="eng-error" role="alert">{error}</p>}<button className="primary" disabled={busy||!valid||s.busy||Object.keys(s.inputDrafts).length>0}>生成变更并审查 <ArrowRight size={15}/></button></form><div className="generator-preview">{valid?<CableModelView cable={draft}/>:<p>请输入有效尺寸后预览。</p>}</div></div></Modal>;
}
interface Standard {id:string;designation:string;title:string;category:string;url:string;implementation:string;scope:string}
interface Basis {reference_ids:string[];rated_voltage_kv:number;highest_voltage_kv:number;environment:string;note:string}
interface BasisCheck {can_record:boolean;compliance:string;statement:string;findings:{code:string;level:string;message:string}[]}
export function StandardsPanel(){const s=useStudio();const [standards,setStandards]=useState<Standard[]>([]),[date,setDate]=useState('');
 const [basis,setBasis]=useState<Basis>((s.w!.design_basis as unknown as Basis)??{reference_ids:[],rated_voltage_kv:20,highest_voltage_kv:24,environment:'buried',note:''});
 const [result,setResult]=useState<BasisCheck|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{void api<{items:Standard[];verified_on:string}>('/api/runtime/standards').then(r=>{setStandards(r.items);setDate(r.verified_on)}).catch(e=>setError(errorText(e)))},[]);
 function update(next:Basis){setBasis(next);setResult(null)}
 async function inspect(){setBusy(true);setError('');try{setResult(await engineeringCall(s.w!.id,s.w!.revision,'standards.inspect',basis))}catch(e){setError(errorText(e))}finally{setBusy(false)}}
 async function propose(){setBusy(true);setError('');try{s.adoptProposal(await engineeringCall(s.w!.id,s.w!.revision,'standards.propose',basis))}catch(e){setError(errorText(e))}finally{setBusy(false)}}
 return <div className="basis-layout"><section><h2>标准目录</h2><p className="eng-note">已核对题录：{date}。条款实现状态与标准有效状态是两回事。</p><div className="standard-list">{standards.map(t=><label className="standard-entry" key={t.id}><input type="checkbox" checked={basis.reference_ids.includes(t.id)} onChange={e=>update({...basis,reference_ids:e.target.checked?[...basis.reference_ids,t.id]:basis.reference_ids.filter(x=>x!==t.id)})}/><div><span className="category">{t.category}</span><strong>{t.designation}</strong><span>{t.title}</span><p>{t.scope}</p><a href={t.url} target="_blank" rel="noreferrer">官方题录 ↗</a></div><em>{t.implementation==='unsupported'?'未实现':t.implementation==='partial_reference'?'部分方法参考':'题录与范围'}</em></label>)}</div></section><section className="basis-editor"><h2>项目设计依据</h2><form onSubmit={e=>{e.preventDefault();void inspect()}}><label>额定电压 U / kV<input aria-label="设计额定电压" type="number" required step="any" min={.1} max={110} value={basis.rated_voltage_kv||''} onChange={e=>update({...basis,rated_voltage_kv:Number(e.target.value)})}/></label><label>设备最高电压 Um / kV<input aria-label="设计最高电压" type="number" required step="any" min={.1} max={126} value={basis.highest_voltage_kv||''} onChange={e=>update({...basis,highest_voltage_kv:Number(e.target.value)})}/></label><label>敷设环境<select aria-label="设计敷设环境" value={basis.environment} onChange={e=>update({...basis,environment:e.target.value})}><option value="buried">均匀土壤直埋 · 单回路</option><option value="vertical_air">空气中竖向敷设 · 单根隔离</option><option value="duct">排管（尚无求解器）</option><option value="shaft_bundle">竖井成束（尚无求解器）</option></select></label><label>参数及环境依据<textarea aria-label="设计依据说明" value={basis.note} maxLength={1000} onChange={e=>update({...basis,note:e.target.value})}/></label><button className="primary" disabled={busy||s.busy}>检查适用范围</button></form>{error&&<p className="eng-error" role="alert">{error}</p>}{result&&<div className="basis-check"><h3>{result.can_record?'可记录为设计参考':'存在不适用项'}</h3><p>{result.statement}</p>{result.findings.map((f,i)=><p className={f.level==='error'?'eng-error':'eng-note'} key={i}>{f.message}</p>)}<button disabled={!result.can_record||busy||s.busy} onClick={()=>void propose()}>提交依据变更审查</button></div>}<p className="eng-note">未内置受版权限制的标准全文或限值表；不会把原型算法包装成完整 IEC／GB 计算。</p></section></div>;
}
interface Trace {tasks:{id:string;capability:string;base_revision:number;status:string;created:string}[];nodes:{id:string;label:string}[];edges:{from:string;to:string;relation:string;page?:number;quote?:string}[];coverage:string}
export function TaskJournal(){const {w}=useStudio();const [data,setData]=useState<Trace|null>(null),[error,setError]=useState('');useEffect(()=>{void api<Trace>(`/api/runtime/${w!.id}/provenance`).then(setData).catch(e=>setError(errorText(e)))},[w!.id,w!.revision]);const label=(id:string)=>data?.nodes.find(n=>n.id===id)?.label??id;return <div className="journal">{error&&<p role="alert">{error}</p>}<h2>工程任务记录</h2><p className="eng-note">{data?.coverage}</p><table className="eng-table"><thead><tr><th>任务</th><th>输入版本</th><th>状态</th><th>时间</th></tr></thead><tbody>{data?.tasks.map(t=><tr key={t.id}><td>{label('task:'+t.id)}</td><td>{t.base_revision}</td><td>{({succeeded:'已完成',running:'执行中',failed:'失败'} as Record<string,string>)[t.status]}</td><td>{new Date(t.created).toLocaleString()}</td></tr>)}</tbody></table>{!data?.tasks.length&&<p className="eng-note">通过新执行层完成一次计算或模型生成后，这里会出现记录。</p>}<h2>输入与引用关系</h2><table className="eng-table"><thead><tr><th>工程对象</th><th>关系</th><th>依据</th></tr></thead><tbody>{data?.edges.map((e,i)=><tr key={i}><td>{label(e.from)}</td><td>{e.relation}</td><td>{label(e.to)}{e.page&&` / 第 ${e.page} 页`}{e.quote&&<blockquote>{e.quote}</blockquote>}</td></tr>)}</tbody></table></div>}
