import {createRoot} from 'react-dom/client';
import {lazy,Suspense} from 'react';
import EngineeringWorkspace from './EngineeringWorkspace';
import EnterpriseWorkspace from './EnterpriseWorkspace';
import DualModeApp from './dual-mode/DualModeApp';
const LegacyStudio=lazy(()=>import('./Studio'));
const params=new URLSearchParams(location.search);
const legacy=params.get('legacy')==='1';
const classic=params.get('classic')==='1';
const enterprise=params.get('enterprise')==='1';
createRoot(document.getElementById('root')!).render(legacy?<Suspense fallback={<p>正在打开迁移界面…</p>}><LegacyStudio/></Suspense>:classic?<EngineeringWorkspace/>:enterprise?<EnterpriseWorkspace/>:<DualModeApp/>);
