import {readFileSync, writeFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {resolve, dirname} from 'node:path';
const root=resolve(dirname(fileURLToPath(import.meta.url)),'..');
const input=JSON.parse(readFileSync(resolve(root,'frontend/src/design-system/tokens.json'),'utf8'));
if(input.schema_version!==1||!Array.isArray(input.scope))throw new Error('Unknown token source');
const css='/* Generated by scripts/build_design_tokens.mjs. Edit tokens.json, not this file. */\n'+
 ':where('+input.scope.join(', ')+') {\n'+Object.entries(input.tokens).map(([key,value])=>{
  if(!/^[a-z][a-z0-9-]*$/.test(key)||typeof value!=='string'||/[;{}]/.test(value))throw new Error('Invalid token: '+key);
  return `  --wb-${key}: ${value};`;
 }).join('\n')+'\n}\n';
const target=resolve(root,'frontend/src/design-system/tokens.css');
if(process.argv.includes('--check')){if(readFileSync(target,'utf8')!==css)throw new Error('Generated tokens are stale');}
else writeFileSync(target,css);
